# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('weight', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='URL of the recipe')),
                ('reference', models.CharField(blank=True, help_text='A page number in a book', max_length=254)),
                ('time', models.DurationField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.Meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ManyToManyField(related_name='meals', to='recipes.MealCategory'),
        ),
    ]
