# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcategory',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
