# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 17:04
from __future__ import unicode_literals

from django.db import migrations

def set_added_by(apps, schema_editor):
    User = apps.get_model('auth','User')
    Meal = apps.get_model('recipes','Meal')
    Recipe = apps.get_model('recipes','Recipe')

    u = User.objects.first()
    print(u)

    for meal in Meal.objects.all():
        meal.added_by = u
        print(meal)
        meal.save()

    print(Recipe.objects.count())
    for recipe in Recipe.objects.all():
        recipe.added_by = u
        print(recipe)
        recipe.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20160404_2125'),
    ]

    operations = [
        migrations.RunPython(set_added_by,migrations.RunPython.noop),
    ]
