# Generated by Django 2.2.1 on 2020-03-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20160405_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='emoji',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
